inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/support/**/*'

Layout/LineLength:
  Max: 100

Metrics/AbcSize: # ✅ fixed extra space
  Max: 17

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Rails:
  Enabled: true

RSpec:
  Enabled: true

Performance:
  Enabled: true

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribeSymbol:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/NamedSubject:
  Enabled: false

# ❌ Removed invalid/unsupported cops:
# - RSpec/DescribeRequest does not exist
# - Capybara cops require rubocop-capybara
# - FactoryBot cops require rubocop-factory_bot
