version: 2.1

executors:
  ruby-executor:
    docker:
      - image: cimg/ruby:3.2.2
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: postgres
      - image: cimg/postgres:14.7
        name: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ohana_site_test
          POSTGRES_PASSWORD: postgres
    working_directory: ~/app

jobs:
  setup:
    executor: ruby-executor
    steps:
      - checkout

      - run:
          name: Install OS dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libvips postgresql-client curl
            curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
            corepack enable

      - run:
          name: Install Ruby dependencies
          command: |
            gem install bundler -v 2.4.10
            bundle _2.4.10_ install --jobs=4 --retry=3

      - run:
          name: Install JS dependencies
          command: yarn install

      - restore_cache:
          keys:
            - v1-assets-{{ checksum "yarn.lock" }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Build JavaScript assets with esbuild
          command: yarn build

      - run:
          name: Precompile Rails assets
          command: RAILS_ENV=production bundle exec rails assets:precompile

      - save_cache:
          paths:
            - public/assets
            - tmp/cache/assets
          key: v1-assets-{{ checksum "yarn.lock" }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Set up database
          command: bin/rails db:create db:schema:load

      - run:
          name: Trigger Render Deploy
          command: |
            curl -X POST https://api.render.com/deploy/srv-d0thl7qdbo4c739n1id0?key=_xE7v0GU4RQ

  test:
    executor: ruby-executor
    steps:
      - checkout

      - run:
          name: Install Ruby dependencies
          command: |
            gem install bundler -v 2.4.10
            bundle _2.4.10_ install --jobs=4 --retry=3

      - run:
          name: Run RSpec
          command: bin/rspec

workflows:
  version: 2
  test_app:
    jobs:
      - setup
      - test:
          requires:
            - setup
