version: 2.1

executors:
  ruby-executor:
    docker:
      - image: cimg/ruby:3.2.2
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: postgres
      - image: cimg/postgres:14.7
        name: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ohana_site_test
          POSTGRES_PASSWORD: postgres
    working_directory: ~/app

jobs:
  setup:
    executor: ruby-executor
    steps:
      - checkout
      - run:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libvips postgresql-client
            gem install bundler -v 2.4.10
            bundle _2.4.10_ install --jobs=4 --retry=3
      - run:
          name: Wait for Postgres
          command: |
            for i in {1..10}; do
              nc -z postgres 5432 && echo "Postgres is up!" && break
              echo "Waiting for Postgres..."
              sleep 2
            done
      - run:
          name: Set up database
          command: bin/rails db:create db:schema:load

  test:
    executor: ruby-executor
    steps:
      - checkout
      - run:
          name: Run RSpec
          command: bin/rspec

workflows:
  version: 2
  test_app:
    jobs:
      - setup
      - test:
          requires:
            - setup
