name: Send Weekly Site Report

on:
  schedule:
    - cron: '0 9 * * 1' # Every Monday at 9:00 UTC
  workflow_dispatch:

jobs:
  email-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # adjust to match your app

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --without development test

      - name: Run report task
        env:
          RAILS_ENV: production
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SITE_EMAIL_TO: ${{ secrets.SITE_EMAIL_TO }}
        run: bundle exec rake reports:send_site_stats
