name: Send Monthly Site Stats Report

on:
  schedule:
    - cron: '0 9 1 * *' # Runs at 9 AM UTC on the 1st of every month

jobs:
  trigger-render-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render one-off job
        run: |
          curl -X POST https://api.render.com/v1/jobs \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "serviceId": "${{ secrets.RENDER_SERVICE_ID }}",
              "startCommand": "bundle exec rake reports:send_site_stats"
            }'
